export const POSTAL_CODE_PATTERNS: Record<string, RegExp> = {
  DE: /^\d{5}$/,
  FR: /^\d{5}$/,
  IT: /^\d{5}$/,
  ES: /^\d{5}$/,
  BE: /^\d{4}$/,
  AT: /^\d{4}$/,
  CH: /^\d{4}$/,
  NO: /^\d{4}$/,
  DK: /^\d{4}$/,
  FI: /^\d{5}$/,
  AU: /^\d{4}$/,
  NZ: /^\d{4}$/,
  CN: /^\d{6}$/,
  IN: /^\d{6}$/,
  RU: /^\d{6}$/,
  TR: /^\d{5}$/,
  PL: /^\d{2}-\d{3}$/,
  PT: /^\d{4}-\d{3}$/,
  AZ: /^AZ\s?\d{4}$/i,
  JP: /^\d{3}-?\d{4}$/,
  BR: /^\d{5}-?\d{3}$/,
  SE: /^\d{3}\s?\d{2}$/,
  US: /^\d{5}(-\d{4})?$/,
  NL: /^\d{4}\s?[A-Z]{2}$/i,
  CA: /^[A-Z]\d[A-Z]\s?\d[A-Z]\d$/i,
  GB: /^[A-Z]{1,2}\d[A-Z\d]?\s?\d[A-Z]{2}$/i,
};
